import Immutable from 'immutable';

export default Immutable.fromJS([
  {
    name: "Mercury",
    symbol: "☿",
    mass: 0.33,
    diameter: 4879,
    density: 5427,
    gravity: 3.7,
    escapeVelocity: 4.3,
    rotationPeriod: 1407.6,
    lengthOfDay: 4222.6,
    distanceFromSun: 57.9,
    perihelion: 46,
    aphelion: 69.8,
    orbitalPeriod: 88,
    orbitalVelocity: 47.4,
    orbitalInclination: 7,
    orbitalEccentricity: 0.205,
    axialTilt: 0.01,
    meanTemperature: 167,
    surfacePressure: 0,
    numberOfMoons: 0,
    ringSystem: false,
    globalMagneticField: true,
    number: 1,
  },
  {
    name: "Venus",
    symbol: "♀",
    mass: 5,
    diameter: 12104,
    density: 5243,
    gravity: 8.9,
    escapeVelocity: 10.4,
    rotationPeriod: -5832.5,
    lengthOfDay: 2802,
    distanceFromSun: 108.2,
    perihelion: 107.5,
    aphelion: 108.9,
    orbitalPeriod: 224.7,
    orbitalVelocity: 35,
    orbitalInclination: 3.4,
    orbitalEccentricity: 0.007,
    axialTilt: 177.4,
    meanTemperature: 464,
    surfacePressure: 92,
    numberOfMoons: 0,
    ringSystem: false,
    globalMagneticField: false,
    number: 2,
  },
  {
    name: "Earth",
    symbol: "♁",
    mass: 6,
    diameter: 12756,
    density: 5514,
    gravity: 9.8,
    escapeVelocity: 11.2,
    rotationPeriod: 23.9,
    lengthOfDay: 24,
    distanceFromSun: 149.6,
    perihelion: 147.1,
    aphelion: 152.1,
    orbitalPeriod: 365.2,
    orbitalVelocity: 29.8,
    orbitalInclination: 0,
    orbitalEccentricity: 0.017,
    axialTilt: 23.4,
    meanTemperature: 15,
    surfacePressure: 1,
    numberOfMoons: 1,
    ringSystem: false,
    globalMagneticField: true,
    number: 3,
  },
  {
    name: "Mars",
    symbol: "♂",
    mass: 0.642,
    diameter: 6792,
    density: 3933,
    gravity: 3.7,
    escapeVelocity: 5,
    rotationPeriod: 24.6,
    lengthOfDay: 24.7,
    distanceFromSun: 227.9,
    perihelion: 206.6,
    aphelion: 249.2,
    orbitalPeriod: 687,
    orbitalVelocity: 24.1,
    orbitalInclination: 1.9,
    orbitalEccentricity: 0.094,
    axialTilt: 25.2,
    meanTemperature: -65,
    surfacePressure: 0.01,
    numberOfMoons: 2,
    ringSystem: false,
    globalMagneticField: false,
    number: 4,
  },
  {
    name: "Jupiter",
    symbol: "♃",
    mass: 1898,
    diameter: 142984,
    density: 1326,
    gravity: 23.1,
    escapeVelocity: 59.5,
    rotationPeriod: 9.9,
    lengthOfDay: 9.9,
    distanceFromSun: 778.6,
    perihelion: 740.5,
    aphelion: 816.6,
    orbitalPeriod: 4331,
    orbitalVelocity: 13.1,
    orbitalInclination: 1.3,
    orbitalEccentricity: 0.049,
    axialTilt: 3.1,
    meanTemperature: -110,
    surfacePressure: null,
    numberOfMoons: 67,
    ringSystem: true,
    globalMagneticField: true,
    number: 5,
  },
  {
    name: "Saturn",
    symbol: "♄",
    mass: 568,
    diameter: 120536,
    density: 687,
    gravity: 9,
    escapeVelocity: 35.5,
    rotationPeriod: 10.7,
    lengthOfDay: 10.7,
    distanceFromSun: 1433.5,
    perihelion: 1352.6,
    aphelion: 1515,
    orbitalPeriod: 10747,
    orbitalVelocity: 9.7,
    orbitalInclination: 2.5,
    orbitalEccentricity: 0.057,
    axialTilt: 26.7,
    meanTemperature: -140,
    surfacePressure: null,
    numberOfMoons: 62,
    ringSystem: true,
    globalMagneticField: true,
    number: 6,
  },
  {
    name: "Uranus",
    symbol: "⛢",
    mass: 87,
    diameter: 51118,
    density: 1271,
    gravity: 8.7,
    escapeVelocity: 21.3,
    rotationPeriod: -17.2,
    lengthOfDay: 17.2,
    distanceFromSun: 2872.5,
    perihelion: 2741.3,
    aphelion: 3004,
    orbitalPeriod: 30589,
    orbitalVelocity: 6.8,
    orbitalInclination: 0.8,
    orbitalEccentricity: 0.046,
    axialTilt: 97.8,
    meanTemperature: -195,
    surfacePressure: null,
    numberOfMoons: 27,
    ringSystem: true,
    globalMagneticField: true,
    number: 7,
  },
  {
    name: "Neptune",
    symbol: "♆",
    mass: 102,
    diameter: 49528,
    density: 1638,
    gravity: 11,
    escapeVelocity: 23.5,
    rotationPeriod: 16.1,
    lengthOfDay: 16.1,
    distanceFromSun: 4495.1,
    perihelion: 4444.5,
    aphelion: 4546,
    orbitalPeriod: 59800,
    orbitalVelocity: 5.4,
    orbitalInclination: 1.8,
    orbitalEccentricity: 0.011,
    axialTilt: 28.3,
    meanTemperature: -200,
    surfacePressure: null,
    numberOfMoons: 14,
    ringSystem: true,
    globalMagneticField: true,
    number: 8,
  },


  {
    name: "units",
    mass: "kg * 10^24",
    diameter: "km",
    density: "kg / m^3",
    gravity: "m / s^2",
    escapeVelocity: "km / s",
    rotationPeriod: "hours",
    lengthOfDay: "hours",
    distanceFromSun: "km * 10^6",
    perihelion: "km * 10^6",
    aphelion: "km * 10^6",
    orbitalPeriod: "days",
    orbitalVelocity: "km / s",
    orbitalInclination: "degrees",
    axialTilt: "degrees",
    meanTemperature: "Celsius",
    surfacePressure: "bars",
  },
]);